# _config.yaml
title: "Pantrify"
description: "Aplikasi yang membantu pengguna menemukan resep masakan berdasarkan bahan yang dimiliki, dengan pencarian berbasis suara, filter kategori, rekomendasi AI, dan manajemen stok bahan makanan."
theme: "jekyll-theme-cayman"
