remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pantrify
description: Pantrify, aplikasi yang membantu pengguna menemukan resep masakan berdasarkan bahan yang dimiliki, dengan pencarian berbasis suara, filter kategori, rekomendasi AI, dan manajemen stok bahan makanan.
